let
    Source = Csv.Document(File.Contents("C:\Users\USer\OneDrive - University of Reading\CS3IP16 - Individual Project\Better Data\Flight Punctuality Summary\2012 Flight Punctuality.csv"),[Delimiter=",", Columns=20, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"run_date", type text}, {"reporting_period", Int64.Type}, {"reporting_airport", type text}, {"origin_destination_country", type text}, {"origin_destination", type text}, {"airline_name", type text}, {"scheduled_charter", type text}, {"number_flights_matched", type number}, {"actual_flights_unmatched", type number}, {"early_to_15_mins_late_percent", type number}, {"flts_16_to_30_mins_late_percent", type number}, {"flts_31_to_60_mins_late_percent", type number}, {"flts_61_to_180_mins_late_percent", type number}, {"flts_181_to_360_mins_late_percent", type number}, {"more_than_360_mins_late_percent", type number}, {"average_delay_mins", type number}, {"planned_flights_unmatched", type number}, {"previous_year_month_flights_matched", type number}, {"previous_year_month_early_to_15_mins_late_percent", type number}, {"previous_year_month_average_delay", type number}})
in
    #"Changed Type"
