let
    Source = Csv.Document(File.Contents("C:\Users\USer\OneDrive - University of Reading\CS3IP16 - Individual Project\Better Data\Flight Punctuality Summary\2019 Flight Punctuality.csv"),[Delimiter=",", Columns=25, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"run_date", type datetime}, {"reporting_period", Int64.Type}, {"reporting_airport", type text}, {"origin_destination_country", type text}, {"origin_destination", type text}, {"airline_name", type text}, {"scheduled_charter", type text}, {"number_flights_matched", Int64.Type}, {"actual_flights_unmatched", Int64.Type}, {"number_flights_cancelled", Int64.Type}, {"flights_more_than_15_minutes_early_percent", type number}, {"flights_15_minutes_early_to_1_minute_early_percent", type number}, {"flights_0_to_15_minutes_late_percent", type number}, {"flights_between_16_and_30_minutes_late_percent", type number}, {"flights_between_31_and_60_minutes_late_percent", type number}, {"flights_between_61_and_120_minutes_late_percent", type number}, {"flights_between_121_and_180_minutes_late_percent", type number}, {"flights_between_181_and_360_minutes_late_percent", type number}, {"flights_more_than_360_minutes_late_percent", type number}, {"flights_unmatched_percent", type number}, {"flights_cancelled_percent", type number}, {"average_delay_mins", type number}, {"previous_year_month_flights_matched", Int64.Type}, {"previous_year_month_early_to_15_mins_late_percent", type number}, {"previous_year_month_average_delay", type number}})
in
    #"Changed Type"
