let
    Source = Csv.Document(File.Contents("C:\Users\USer\OneDrive - University of Reading\CS3IP16 - Individual Project\Better Data\Flight Punctuality Summary\2016 Flight Punctuality.csv"),[Delimiter=",", Columns=20, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"run_date", type text}, {"reporting_period", Int64.Type}, {"reporting_airport", type text}, {"origin_destination_country", type text}, {"origin_destination", type text}, {"airline_name", type text}, {"scheduled_charter", type text}, {"number_flights_matched", Int64.Type}, {"actual_flights_unmatched", Int64.Type}, {"early_to_15_mins_late_percent", type number}, {"flts_16_to_30_mins_late_percent", type number}, {"flts_31_to_60_mins_late_percent", type number}, {"flts_61_to_180_mins_late_percent", type number}, {"flts_181_to_360_mins_late_percent", type number}, {"more_than_360_mins_late_percent", type number}, {"average_delay_mins", type number}, {"planned_flights_unmatched", Int64.Type}, {"previous_year_month_flights_matched", Int64.Type}, {"previous_year_month_early_to_15_mins_late_percent", type number}, {"previous_year_month_average_delay", type number}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"early_to_15_mins_late_percent", "flights_0_to_15_minutes_late_percent"}, {"flts_16_to_30_mins_late_percent", "flights_between_16_and_30_minutes_late_percent"}, {"flts_31_to_60_mins_late_percent", "flights_between_31_and_60_minutes_late_percent"}, {"flts_61_to_180_mins_late_percent", "flights_between_61_and_120_minutes_late_percent"}, {"flts_181_to_360_mins_late_percent", "flights_between_121_and_180_minutes_late_percent"}, {"more_than_360_mins_late_percent", "flights_more_than_360_minutes_late_percent"}})
in
    #"Renamed Columns"
