% Change Flights = 
DIVIDE(
 CALCULATE(
 SUM(FACT_UK_AIRLINE_INFO[Number of Flights]), 
 FILTER(DIM_AIRLINE_DETAILS,DIM_AIRLINE_DETAILS[Year]=MAX(DIM_AIRLINE_DETAILS[Year])
 )
 ), 
 CALCULATE(
 SUM(FACT_UK_AIRLINE_INFO[Number of Flights]),
 FILTER(DIM_AIRLINE_DETAILS,DIM_AIRLINE_DETAILS[Year]=MIN(DIM_AIRLINE_DETAILS[Year])))
,0) 
- 1
