% Delay Time CHANGE = 
DIVIDE(
 CALCULATE(
 AVERAGE(FACT_FLIGHT_and_AIRPORT_INFO[Average Delay (Mins)]), 
 FILTER(DIM_AIRPORT_DETAILS,DIM_AIRPORT_DETAILS[Year]=MAX(DIM_AIRPORT_DETAILS[Year])
 )
 ), 
 CALCULATE(
 AVERAGE(FACT_FLIGHT_and_AIRPORT_INFO[Average Delay (Mins)]),
 FILTER(DIM_AIRPORT_DETAILS,DIM_AIRPORT_DETAILS[Year]=MIN(DIM_AIRPORT_DETAILS[Year])))
,0) 
- 1
