% Flights CHANGE = 
DIVIDE(
 CALCULATE(
 SUM(FACT_FLIGHT_and_AIRPORT_INFO[Number of Flights]), 
 FILTER(DIM_AIRPORT_DETAILS,DIM_AIRPORT_DETAILS[Year]=MAX(DIM_AIRPORT_DETAILS[Year])
 )
 ), 
 CALCULATE(
 SUM(FACT_FLIGHT_and_AIRPORT_INFO[Number of Flights]),
 FILTER(DIM_AIRPORT_DETAILS,DIM_AIRPORT_DETAILS[Year]=MIN(DIM_AIRPORT_DETAILS[Year])))
,0) 
- 1
