% Passengers CHANGE = 
DIVIDE(
 CALCULATE(
 SUMX(DISTINCT(DIM_AIRPORT_DETAILS[Airport Year Key]), FIRSTNONBLANK(DIM_AIRPORT_DETAILS[Number of Passengers at Airport for Year], 0)), 
 FILTER(DIM_AIRPORT_DETAILS,DIM_AIRPORT_DETAILS[Year]=MAX(DIM_AIRPORT_DETAILS[Year])
 )
 ), 
 CALCULATE(
 SUMX(DISTINCT(DIM_AIRPORT_DETAILS[Airport Year Key]), FIRSTNONBLANK(DIM_AIRPORT_DETAILS[Number of Passengers at Airport for Year], 0)),
 FILTER(DIM_AIRPORT_DETAILS,DIM_AIRPORT_DETAILS[Year]=MIN(DIM_AIRPORT_DETAILS[Year])))
,0) 
- 1
