let
    Source = Table.Combine({#"2016 Flight Punctuality", #"2017 Flight Punctuality", #"2018 Flight Punctuality", #"2019 Flight Punctuality", #"2020 Flight Punctuality", #"2021 Flight Punctuality", #"2010 Flight Punctuality", #"2011 Flight Punctuality", #"2012 Flight Punctuality", #"2013 Flight Punctuality", #"2014 Flight Punctuality", #"2015 Flight Punctuality"}),
    #"Removed Blank Rows" = Table.SelectRows(Source, each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
    #"Removed Columns" = Table.RemoveColumns(#"Removed Blank Rows",{"run_date", "origin_destination", "actual_flights_unmatched", "flights_unmatched_percent", "planned_flights_unmatched", "previous_year_month_flights_matched", "previous_year_month_early_to_15_mins_late_percent", "previous_year_month_average_delay"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns",{"reporting_period", "reporting_airport", "origin_destination_country", "airline_name", "scheduled_charter", "number_flights_matched", "flights_cancelled_percent", "number_flights_cancelled", "average_delay_mins", "flights_more_than_15_minutes_early_percent", "flights_15_minutes_early_to_1_minute_early_percent", "flights_0_to_15_minutes_late_percent", "flights_between_16_and_30_minutes_late_percent", "flights_between_31_and_60_minutes_late_percent", "flights_between_61_and_120_minutes_late_percent", "flights_between_121_and_180_minutes_late_percent", "flights_between_181_and_360_minutes_late_percent", "flights_more_than_360_minutes_late_percent", "early_to_15_mins_late_percent", "flts_16_to_30_mins_late_percent", "flts_31_to_60_mins_late_percent", "flts_61_to_180_mins_late_percent", "flts_181_to_360_mins_late_percent", "more_than_360_mins_late_percent"}),
    #"Replaced Value" = Table.ReplaceValue(#"Reordered Columns",null,0,Replacer.ReplaceValue,{"flights_more_than_15_minutes_early_percent", "flights_15_minutes_early_to_1_minute_early_percent", "flights_0_to_15_minutes_late_percent", "flights_between_16_and_30_minutes_late_percent", "flights_between_31_and_60_minutes_late_percent", "flights_between_61_and_120_minutes_late_percent", "flights_between_121_and_180_minutes_late_percent", "flights_between_181_and_360_minutes_late_percent", "flights_more_than_360_minutes_late_percent", "early_to_15_mins_late_percent", "flts_16_to_30_mins_late_percent", "flts_31_to_60_mins_late_percent", "flts_61_to_180_mins_late_percent", "flts_181_to_360_mins_late_percent", "more_than_360_mins_late_percent"}),
    #"Early Flights" = Table.AddColumn(#"Replaced Value", "Flights Early or On Time (%)", each ([flights_more_than_15_minutes_early_percent] + [flights_15_minutes_early_to_1_minute_early_percent] + [early_to_15_mins_late_percent])/100),
    #"5-30 mins" = Table.AddColumn(#"Early Flights", "Flights 5-30 Mins Late (%)", each ([flights_0_to_15_minutes_late_percent] + [flights_between_16_and_30_minutes_late_percent] + [flts_16_to_30_mins_late_percent])/100),
    #"30-60 mins" = Table.AddColumn(#"5-30 mins", "Flights 30-60 Mins Late (%)", each ([flights_between_31_and_60_minutes_late_percent] + [flts_31_to_60_mins_late_percent])/100),
    #"60-120 mins" = Table.AddColumn(#"30-60 mins", "Flights 1-2 Hours Late (%)", each ([flights_between_61_and_120_minutes_late_percent] + [flts_61_to_180_mins_late_percent])/100),
    #"120 mins +" = Table.AddColumn(#"60-120 mins", "Flights 2+ Hours Late (%)", each ([flights_between_121_and_180_minutes_late_percent] + [flights_between_181_and_360_minutes_late_percent] + [flights_more_than_360_minutes_late_percent] + [flts_181_to_360_mins_late_percent] + [more_than_360_mins_late_percent])/100),
    #"Replaced Value3" = Table.ReplaceValue(#"120 mins +",null,0,Replacer.ReplaceValue,{"flights_cancelled_percent"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3",null,0,Replacer.ReplaceValue,{"number_flights_cancelled"}),
    #"Removed Columns1" = Table.RemoveColumns(#"Replaced Value4",{"flights_more_than_15_minutes_early_percent", "flights_15_minutes_early_to_1_minute_early_percent", "flights_0_to_15_minutes_late_percent", "flights_between_16_and_30_minutes_late_percent", "flights_between_31_and_60_minutes_late_percent", "flights_between_61_and_120_minutes_late_percent", "flights_between_121_and_180_minutes_late_percent", "flights_between_181_and_360_minutes_late_percent", "flights_more_than_360_minutes_late_percent"}),
    #"Added Custom" = Table.AddColumn(#"Removed Columns1", "Flights Cancelled (%)", each [flights_cancelled_percent] / 100),
    #"Removed Columns2" = Table.RemoveColumns(#"Added Custom",{"flights_cancelled_percent"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns2",{{"Flights Early or On Time (%)", Percentage.Type}, {"Flights 5-30 Mins Late (%)", Percentage.Type}, {"Flights 30-60 Mins Late (%)", Percentage.Type}, {"Flights 1-2 Hours Late (%)", Percentage.Type}, {"Flights 2+ Hours Late (%)", Percentage.Type}, {"Flights Cancelled (%)", Percentage.Type}}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Changed Type",{"reporting_period", "reporting_airport", "origin_destination_country", "airline_name", "scheduled_charter", "number_flights_matched", "Flights Cancelled (%)", "number_flights_cancelled", "average_delay_mins", "Flights Early or On Time (%)", "Flights 5-30 Mins Late (%)", "Flights 30-60 Mins Late (%)", "Flights 1-2 Hours Late (%)", "Flights 2+ Hours Late (%)"}),
    #"Replaced Value5" = Table.ReplaceValue(#"Reordered Columns1",201612,2016,Replacer.ReplaceValue,{"reporting_period"}),
    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5",201712,2017,Replacer.ReplaceValue,{"reporting_period"}),
    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value6",{{"reporting_period", "Year"}, {"reporting_airport", "Airport Name"}, {"origin_destination_country", "Destination Country"}, {"airline_name", "Airline Name"}}),
    #"Replaced Value7" = Table.ReplaceValue(#"Renamed Columns","C","Charter",Replacer.ReplaceText,{"scheduled_charter"}),
    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","S","Scheduled",Replacer.ReplaceText,{"scheduled_charter"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Replaced Value8",{{"scheduled_charter", "Flight Type"}, {"number_flights_matched", "Number of Flights"}, {"number_flights_cancelled", "Number of Flights Cancelled"}, {"average_delay_mins", "Average Delay (Mins)"}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Average Delay (Mins)", Int64.Type}, {"Year", Int64.Type}, {"Number of Flights Cancelled", Int64.Type}}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type1", "Year", "Year - Copy"),
    #"Changed Type2" = Table.TransformColumnTypes(#"Duplicated Column",{{"Year - Copy", type text}}),
    #"Added Custom1" = Table.AddColumn(#"Changed Type2", "Airport Year Key", each [Airport Name] & [#"Year - Copy"]),
    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom1",{{"Airport Year Key", type text}}),
    #"Removed Columns3" = Table.RemoveColumns(#"Changed Type3",{"Year - Copy"}),
    #"Reordered Columns2" = Table.ReorderColumns(#"Removed Columns3",{"Airport Year Key", "Year", "Airport Name", "Destination Country", "Airline Name", "Flight Type", "Number of Flights", "Flights Cancelled (%)", "Number of Flights Cancelled", "Average Delay (Mins)", "Flights Early or On Time (%)", "Flights 5-30 Mins Late (%)", "Flights 30-60 Mins Late (%)", "Flights 1-2 Hours Late (%)", "Flights 2+ Hours Late (%)"}),
    #"Removed Columns4" = Table.RemoveColumns(#"Reordered Columns2",{"Year", "Airport Name"}),
    #"Merged Queries" = Table.NestedJoin(#"Removed Columns4", {"Airport Year Key"}, DIM_AIRPORT_DETAILS, {"Airport Year Key"}, "DIM_AIRPORT_DETAILS", JoinKind.LeftOuter),
    #"Expanded DIM_AIRPORT_DETAILS" = Table.ExpandTableColumn(#"Merged Queries", "DIM_AIRPORT_DETAILS", {"Number of Flights at Airport for Year", "Number of Passengers at Airport for Year"}, {"Number of Flights at Airport for Year", "Number of Passengers at Airport for Year"}),
    #"Filtered Rows" = Table.SelectRows(#"Expanded DIM_AIRPORT_DETAILS", each ([Number of Flights at Airport for Year] <> null)),
    #"Reordered Columns3" = Table.ReorderColumns(#"Filtered Rows",{"Airport Year Key", "Destination Country", "Airline Name", "Flight Type", "Number of Flights", "Flights Cancelled (%)", "Number of Flights Cancelled", "Average Delay (Mins)", "Flights Early or On Time (%)", "Flights 5-30 Mins Late (%)", "Flights 30-60 Mins Late (%)", "Flights 1-2 Hours Late (%)", "Flights 2+ Hours Late (%)", "Number of Flights at Airport for Year", "Number of Passengers at Airport for Year"}),
    #"Removed Columns5" = Table.RemoveColumns(#"Reordered Columns3",{"early_to_15_mins_late_percent", "flts_16_to_30_mins_late_percent", "flts_31_to_60_mins_late_percent", "flts_61_to_180_mins_late_percent", "flts_181_to_360_mins_late_percent", "more_than_360_mins_late_percent"})
in
    #"Removed Columns5"
